---
sidebar: sidebar 
permalink: learn-eda-workloads.html 
keywords: software builders, development, benefits, eda, electronic design automation, perforce integration, ci, cd 
summary: NetApp Workload Factory for EDA で Perforce 統合を使用する方法を学習します。 
---
= NetApp Workload Factory for EDA における Perforce の統合について学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Perforce を CI/CD パイプラインと統合すると、ビルド、テスト、デプロイメントが自動化され、開発プロセスが強化され、ソフトウェア配信の高速化と信頼性が向上します。

EDA における継続的インテグレーションと継続的デプロイメント (CI/CD) は、ソフトウェア ビルダー向けの迅速なビルド環境作成ツールです。これにより、個人開発環境の迅速なセットアップが可能になり、時間が節約され、開発者のセルフサービスが可能になるとともに、DevOps チームがインフラストラクチャを制御できるようになります。CI/CD を使用すると、ソフトウェア開発者は特殊なデータ ストレージや開発インフラストラクチャの理解を必要とせずに、ワークスペースをすばやく作成できます。



== CI/CD とは何ですか?

CI/CD を使用すると、開発者がソフトウェアのさまざまなバージョンを管理および操作する方法を効率化できます。Perforce Helix Core と連携して、ソフトウェア バージョンを即座に複製し、開発、QA、CI/CD 用のワークスペースを作成します。

プロジェクトを簡単に作成し、ソフトウェア環境とその成果物を表すボリュームを割り当てることができます。ソフトウェアを更新するときに、ボリュームのスナップショットを作成して、その時点でのソフトウェアの状態をキャプチャできます。再同期せずに任意のソフトウェア バージョンに即座にアクセスできるため、時間とリソースを節約できます。

NetApp ONTAPのスナップショット機能とクローン機能を使用すると、ソフトウェアのさまざまなバージョンにすぐにアクセスできるようになり、更新をより迅速に開発およびリリースできます。ワークロードファクトリーの詳細については、 link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["ワークロードファクトリーの概要"^]。



== CI/CD 機能

* プロジェクトを作成、編集、削除します。見る link:manage-projects.html["プロジェクトの管理"]。
* 定義されたソフトウェア バージョンのスナップショットを作成します。見る link:version-projects.html["プロジェクトのバージョンを管理する"]。
* ワークスペースを作成および削除します (クローンに基づいて)。見る link:create-workspaces.html["ワークスペースを作成する"]。
* プロジェクトへのアクセスを制御するためのアクセス ポリシーを作成します。
* 各プロジェクトの容量使用状況を分析します。
* 各プロジェクトのクローンのサイズ制限とクローンの保持を制御します。
* Perforce などのバージョン管理システムと統合します。見る link:integrate-perforce.html["Perforceとの統合"]。




== EDAのプロジェクトとワークスペース

プロジェクトを作成し、ソフトウェア環境とその成果物を表すボリュームを割り当てることができます。ソフトウェアの新しいバージョンを作成するたびに、ボリューム データを再同期し、プロジェクト スナップショットを作成して、ボリュームの状態を既知のバージョンとしてマークする必要があります。プロジェクトのソース ボリュームはローリング アップデートを取得し、複数のバージョンをマークするために複数のスナップショットを持つ場合があります。各スナップショットは、開発者、QA、またはビルド プロセスで使用できる専用または共有の編集可能なリポジトリであるインスタント クローンとしてすぐに使用できます。特定のソフトウェア バージョンのコンテキストにおけるクローンとは、ワークスペースのことです。



== Workload Factory Codebox による自動化

ワークロード ファクトリーでは、_Codebox_ による組み込みの自動化が導入されています。Codebox は次のような自動化の利点を提供します。

* *コード スニペットの生成*: リソースの作成中に Infrastructure-as-Code (IaC) スニペットが生成され、既存のオーケストレーション ワークフローとのシームレスな統合が可能になります。
* *Infrastructure-as-code のコパイロット*: Codebox は、開発者と DevOps が Workload Factory でサポートされているあらゆる操作を実行するためのコードを生成するのに役立つ Infrastructure-as-code (IaC) コパイロットです。
* *コード ビューアと自動化カタログ*: Codebox は、自動化をすばやく分析するためのコード ビューアと、将来の再利用を迅速に行うための自動化カタログを提供します。




== 料金

Workload Factory の CI/CD 機能の使用には料金はかかりません。



== ライセンス

Workload Factory の CI/CD 機能を使用するために、 NetAppからの特別なライセンスは必要ありません。



== 地域

EDA は、FSx for ONTAPがサポートされているすべての商用リージョンでサポートされています。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポートされている Amazon リージョンを表示します。"^]

次の AWS リージョンはサポートされていません。

* 中国地域
* GovCloud（米国）リージョン
* シークレットクラウド
* トップシークレットクラウド




== 助けを得る

Amazon FSx for NetApp ONTAPは、AWS ファーストパーティソリューションです。サポートについては、AWS マネジメントコンソールのサポートセンターを使用してケースを開いてください。「FSx for ONTAP」とカテゴリを選択し、必要な情報を入力します。

Workload FactoryまたはWorkload Factoryアプリケーションとサービスに関する一般的な質問については、以下を参照してください。 link:get-help-eda.html["Workload Factory 向け EDA のヘルプを入手する"]。
