---
sidebar: sidebar 
permalink: learn-eda.html 
keywords: software builders, development, benefits, eda, electronic design automation 
summary: NetApp Workload Factory for EDA は、FSx for ONTAPの使用パフォーマンスを最適化するのに役立ちます。 
---
= EDA向けNetApp Workload Factoryの詳細
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for EDA は、複数のファイルシステムにわたって FSx for ONTAPを最適化するのに役立ちます。ストレージ パラメータを自動化し、パフォーマンス制約を分析し、EDA プロジェクトに関する分析情報を取得することで、パフォーマンスを最適化し、運用コストを削減できます。

これは、Infrastructure as Code (IaC) フレームワークと統合するように設計されています。

Workload Factory for EDA は、複数の FSx for ONTAPファイル システムの管理に役立つダッシュボード、ストレージ自動化フレームワーク、ユーティリティを提供します。

以下の機能を提供します:

* link:task-use-overview-dashboard.html["概要ダッシュボード"]：一元化されたクラスタビューを提供し、FSx for ONTAPクラスタの健全性、容量、スループットの監視、新しいボリュームの配置場所の決定、容量の拡張とスループットに関する情報に基づいた意思決定を支援します。
* link:task-monitor-latency.html["FSx レイテンシ分析"]：設定可能な警告および重大なイベントしきい値を使用して、ボリュームの読み取りおよび書き込みの遅延パフォーマンスをプロアクティブに監視します。ONTAP QoS遅延センターメトリックを使用した自動化された基本分析が含まれています。
* link:task-configure-dashboard.html["プロジェクトダッシュボード"]：FSx for ONTAPファイルシステム全体のストレージ消費量を一元的に表示し、プロジェクト全体のストレージ使用状況に関する計画、コストの評価、情報の収集を支援します。
* link:learn-eda-workloads.html["CI/CD"]: FSx for ONTAPボリューム クローン機能を活用して、ソフトウェアのビルド時間を効率化し、短縮します。

